#!/bin/bash

# tmp/db is for postgres, don't touch

./docker-build

set -xv

docker rm -f adm
docker run --name adm -d -p 8989:8989 -v /etc/letsencrypt:/etc/letsencrypt hubs scripts/admin
docker logs -f adm &
