#!/bin/bash

mkdir -p mycerts
sudo cp /etc/letsencrypt/live/codi13.dyndns.org/fullchain.pem mycerts/cert.pem
sudo cp /etc/letsencrypt/live/codi13.dyndns.org/privkey.pem mycerts/key.pem
sudo chown -R $USER mycerts

docker build . -t hubs --network=host
