version: '3.5'
services:
    dialog:
        container_name: dialog
        image: dialog
        ports:
            - "4443:4443"
        networks:
            - vxlab
    db:
        container_name: db
        restart: unless-stopped
        image: postgres:10
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        networks:
            - vxlab
    ret:
        container_name: ret
        #network_mode: host
        image: ret
        #build:
        #  context: .
        #  dockerfile: TurkeyDockerfile
        environment:
            - "DB_HOST=db"
        #command: bash -c "source ~/.bashrc; pushd assets; yarn; popd; mix deps.get; mix ecto.create; mix ecto.migrate; mix phx.server"
        #command: sleep 10000
        command: scripts/start
        volumes:
            - .:/ret
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - vxlab
    #hubs:
    #    container_name: hubs
    #    image: hubs
    #    ports:
    #        - "8080:8080"
    #    depends_on:
    #        - ret
    #    networks:
    #        - vxlab

networks:
    vxlab:
      external: true
      name: vxlab

