version: '3.5'
services:
    #coturn:
    #    container_name: coturn
    #    image: coturn/coturn
    #    ports:
    #        - "3478:3478"
    #        - "3478:3478/udp"
    #        - "5349:5349"
    #        - "5349:5349/udp"
    #        - "49152-65535:49152-65535/udp"
    dialog:
        container_name: dialog
        image: dialog
        environment:
            MEDIASOUP_LISTEN_IP: 131.170.250.215
            MEDIASOUP_ANNOUNCED_IP: 131.170.250.215
        ports:
            - "4443:4443"
#        networks:
#            - vxlab
    db:
        container_name: db
        restart: unless-stopped
        image: postgres:10
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
#        networks:
#            - vxlab
    ret:
        container_name: ret
        #network_mode: host
        image: ret
        #build:
        #  context: .
        #  dockerfile: TurkeyDockerfile
        environment:
            - "DB_HOST=db"
        command: scripts/start
        # command: bash -c "source ~/.bashrc; pushd assets; yarn; popd; mix deps.get; mix ecto.create; mix ecto.migrate; mix phx.server"
        # command: sleep 10000
        volumes:
            - .:/ret
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - /etc/letsencrypt/:/etc/letsencrypt/
        ports:
            - "4000:4000"
        depends_on:
            - db
#        networks:
#            - vxlab
    nginx:
      container_name: nginx
      image: nginx
      ports:
       - "80:80"
       - "443:443"
      volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
       - /etc/letsencrypt/:/etc/letsencrypt/
      command: [nginx-debug, '-g', 'daemon off;']

    #hubs:
    #    container_name: hubs
    #    image: hubs
    #    ports:
    #        - "8080:8080"
    #    depends_on:
    #        - ret
    #    networks:
    #        - vxlab

#networks:
#    vxlab:
#      external: true
#      name: vxlab

